export const nikeProducts = [
  {
    id: 1,
    tags: "Just In",
    title: "Nike Air Force 1 Mid '07",
    description: "Men's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
    imagesUrls: "/images/products/product-1.png",
  },
  {
    id: 2,
    tags: "Just In",
    title: "Nike Court Vision Low Next Nature",
    description: "Men's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 4 995.00",
    imagesUrls: "/images/products/product-2.png",
  },
  {
    id: 3,
    tags: "Just In",
    title: "Nike Air Force 1 PLT.AF.ORM",
    description: "Women's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 8 695.00",
    imagesUrls: "/images/products/product-3.png",
  },
  {
    id: 4,
    tags: "Just In",
    title: "Nike Air Force 1 React",
    description: "Men's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 13 295.00",
    imagesUrls: "/images/products/product-4.png",
  },
  {
    id: 5,
    tags: "Promo Exclusion",
    title: "Air Jordan 1 Elevate Low",
    description: "Women's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 11 895.00",
    imagesUrls: "/images/products/product-5.png",
  },
  {
    id: 6,
    tags: "Just In",
    title: "Nike Standard Issue",
    description: "Women's Basketball Jersey",
    color: "1 Colour",
    price: "MRP : ₹ 2 895.00",
    imagesUrls: "/images/products/product-6.png",
  },
  {
    id: 7,
    tags: "Promo Exclusion",
    title: "Nike Dunk Low Retro SE",
    description: "Men's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 9 695.00",
    imagesUrls: "/images/products/product-7.png",
  },
  {
    id: 8,
    tags: "Sustainable Materials",
    title: "Nike Dri-FIT UV Hyverse",
    description: "Men's Short Sleeve Graphic Fitness Top",
    color: "1 Colour",
    price: "MRP : ₹ 2 495.00",
    imagesUrls: "/images/products/product-8.png",
  },
  {
    id: 9,
    tags: "Just In",
    title: "Nike Court Vision Low",
    description: "Men's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 5 695.00",
    imagesUrls: "/images/products/product-9.png",
  },
  {
    id: 10,
    tags: "Just In",
    title: "Nike Dri-FIT Ready",
    description: "Men's Short Sleeve Fitness Top",
    color: "3 Colours",
    price: "MRP : ₹ 2 495.00",
    imagesUrls: "/images/products/product-10.png",
  },
  {
    id: 11,
    tags: "Just In",
    title: "Nike One Leak Protection: Period",
    description: "Women's Mid-Rise 18cm (approx.) Biker Shorts",
    color: "2 Colours",
    price: "MRP : ₹ 3 395.00",
    imagesUrls: "/images/products/product-11.png",
  },
  {
    id: 12,
    tags: "Just In",
    title: "Nike Air Force 1 LV8 3",
    description: "Older Kids' Shoe",
    color: "1 Colour",
    price: "MRP : ₹ 7 495.00",
    imagesUrls: "/images/products/product-12.png",
  },
  {
    id: 13,
    tags: "Just In",
    title: "Nike Blazer Low Platform",
    description: "Women's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 8 195.00",
    imagesUrls: "/images/products/product-13.png",
  },
  {
    id: 14,
    tags: "Just In",
    title: "Nike Air Force 1 '07",
    description: "Women's Shoe",
    color: "2 Colours",
    price: "MRP : ₹ 8 195.00",
    imagesUrls: "/images/products/product-14.png",
  },
  {
    id: 15,
    tags: "Just In",
    title: "Nike Pro Dri-FIT",
    description: "Men's Tight-Fit Sleeveless Top",
    color: "1 Colour",
    price: "MRP : ₹ 1 495.00",
    imagesUrls: "/images/products/product-15.png",
  },
  {
    id: 16,
    tags: "Just In",
    title: "Nike Dunk Low Retro",
    description: "Men's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 8 695.00",
    imagesUrls: "/images/products/product-16.png",
  },
  {
    id: 17,
    tags: "Just In",
    title: "Nike Air Max SC",
    description: "Women's Shoes",
    color: "2 Colours",
    price: "MRP : ₹ 5 995.00",
    imagesUrls: "/images/products/product-17.png",
  },
  {
    id: 18,
    tags: "Just In",
    title: "Nike Dri-FIT UV Miler",
    description: "Men's Short Sleeve Running Top",
    color: "1 Colour",
    price: "MRP : ₹ 1 695.00",
    imagesUrls: "/images/products/product-18.png",
  },
  {
    id: 19,
    tags: "Just In",
    title: "Nike Air Max SYSTM",
    description: "Older Kids' Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 6 495.00",
    imagesUrls: "/images/products/product-19.png",
  },
  {
    id: 20,
    tags: "Just In",
    title: "Nike Alate All U",
    description: "Women's Light Support Lightly Lined UNeck Printed Sports Bra",
    color: "1 Colour",
    price: "MRP : ₹ 2 195.00",
    imagesUrls: "/images/products/product-20.png",
  },
  {
    id: 21,
    tags: "Just In",
    title: "Nike Court Legacy Lift",
    description: "Women's Shoes",
    color: "2 Colours",
    price: "MRP : ₹ 7 495.00",
    imagesUrls: "/images/products/product-21.png",
  },
  {
    id: 22,
    tags: "Just In",
    title: "Nike Swoosh",
    description: "Women's Medium support Padded Sports Bra Tank",
    color: "2 Colours",
    price: "MRP : ₹ 3 095.00",
    imagesUrls: "/images/products/product-22.png",
  },
  {
    id: 23,
    tags: "Just In",
    title: "Nike SB Zoom Janoski OG+",
    description: "Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 8 595.00",
    imagesUrls: "/images/products/product-23.png",
  },
  {
    id: 24,
    tags: "Just In",
    title: "Nike Dri-FIT Run Division Rise 365",
    description: "Men's Running Tank",
    color: "2 Colours",
    price: "MRP : ₹ 3 495.00",
    imagesUrls: "/images/products/product-24.png",
  },
  {
    id: 25,
    tags: "Just In",
    title: "Nike Dri-FIT Challenger",
    description: "Men's 18cm (approx.) 2-in 1 Versatile Shorts",
    color: "1 Colour",
    price: "MRP : ₹ 2 495.00",
    imagesUrls: "/images/products/product-25.png",
  },
  {
    id: 26,
    tags: "Just In",
    title: "Jordan Series ES",
    description: "Men's Shoes",
    color: "2 Colours",
    price: "MRP : ₹ 7 495.00",
    imagesUrls: "/images/products/product-26.png",
  },
  {
    id: 27,
    tags: "Just In",
    title: "Nike Outdoor Play",
    description: "Older Kids' Oversized Woven Jacket",
    color: "1 Colour",
    price: "MRP : ₹ 3 895.00",
    imagesUrls: "/images/products/product-27.png",
  },
  {
    id: 28,
    tags: "Just In",
    title: "Nike Sportswear Trend",
    description: "Older Kids' (Girls') High waisted Woven Shorts",
    color: "2 Colours",
    price: "MRP : ₹ 2 495.00",
    imagesUrls: "/images/products/product-28.png",
  },
  {
    id: 29,
    tags: "Just In",
    title: "Nike Blazer Low '77 Jumbo",
    description: "Women's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 8 595.00",
    imagesUrls: "/images/products/product-29.png",
  },
  {
    id: 30,
    tags: "Just In",
    title: "Nike SB Force 58",
    description: "Skate Shoe",
    color: "1 Colour",
    price: "MRP : ₹ 5 995.00",
    imagesUrls: "/images/products/product-30.png",
  },
  {
    id: 31,
    tags: "Just In",
    title: "Nike Dri-FIT Run Division Challenger",
    description: "Men's 13cm (approx.) Brief-Lined Running Shorts",
    color: "2 Colours",
    price: "MRP : ₹ 2 495.00",
    imagesUrls: "/images/products/product-31.png",
  },
  {
    id: 32,
    tags: "Just In",
    title: "Nike Legend Essential 3 Next Nature",
    description: "Men's Training Shoes",
    color: "2 Colours",
    price: "MRP : ₹ 4 995.00",
    imagesUrls: "/images/products/product-32.png",
  },
  {
    id: 33,
    tags: "Just In",
    title: "Nike Air Max SYSTM",
    description: "Women's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 8 595.00",
    imagesUrls: "/images/products/product-33.png",
  },
  {
    id: 34,
    tags: "Just In",
    title: "Nike Dri-FIT Totality",
    description: "Men's 23cm (approx.) Unlined Shorts",
    color: "2 Colours",
    price: "MRP : ₹ 1 795.00",
    imagesUrls: "/images/products/product-34.png",
  },
  {
    id: 35,
    tags: "Just In",
    title: "Serena Williams Design Crew",
    description: "Women's Full zip Top",
    color: "1 Colour",
    price: "MRP : ₹ 5 495.00",
    imagesUrls: "/images/products/product-35.png",
  },
  {
    id: 36,
    tags: "Just In",
    title: "Jordan Why Not .6 PF",
    description: "Men's Shoes",
    color: "2 Colours",
    price: "MRP : ₹ 13 995.00",
    imagesUrls: "/images/products/product-36.png",
  },
  {
    id: 37,
    tags: "Promo Exclusion",
    title: "Air Jordan 1 Low",
    description: "Women's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 8 295.00",
    imagesUrls: "/images/products/product-37.png",
  },
  {
    id: 38,
    tags: "Just In",
    title: "Nike Dri-FIT ADV TechKnit Ultra",
    description: "Men's Short Sleeve Running Top",
    color: "1 Colour",
    price: "MRP : ₹ 3 895.00",
    imagesUrls: "/images/products/product-38.png",
  },
  {
    id: 39,
    tags: "Just In",
    title: "Nike Dri-FIT Form",
    description: "Men's 18cm (approx.) Unlined Versatile Shorts",
    color: "2 Colours",
    price: "MRP : ₹ 2 395.00",
    imagesUrls: "/images/products/product-39.png",
  },
  {
    id: 40,
    tags: "Promo Exclusion",
    title: "Air Jordan 1 Mid",
    description: "Women's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 11 495.00",
    imagesUrls: "/images/products/product-40.png",
  },
  {
    id: 41,
    tags: "Just In",
    title: "Nike Dri-FIT ADV Run Division",
    description: "Women's Long-Sleeve Running Top",
    color: "1 Colour",
    price: "MRP : ₹ 5 295.00",
    imagesUrls: "/images/products/product-41.png",
  },
  {
    id: 42,
    tags: "Just In",
    title: "Nike Yoga",
    description: "Women's High Waisted 7/8 Leggings",
    color: "1 Colour",
    price: "MRP : ₹ 3 795.00",
    imagesUrls: "/images/products/product-42.png",
  },
  {
    id: 43,
    tags: "Just In",
    title: "Nike Dri-FIT Totality",
    description: "Men's 18cm (approx.) Unlined Shorts",
    color: "3 Colours",
    price: "MRP : ₹ 1 795.00",
    imagesUrls: "/images/products/product-43.png",
  },
  {
    id: 44,
    tags: "Just In",
    title: "Nike Dri-FIT ADV Tour",
    description: "Women's Short sleeve Golf Polo",
    color: "2 Colours",
    price: "MRP : ₹ 3 695.00",
    imagesUrls: "/images/products/product-44.png",
  },
  {
    id: 45,
    tags: "Just In",
    title: "Nike Tanjun",
    description: "Women's Shoes",
    color: "2 Colours",
    price: "MRP : ₹ 4 995.00",
    imagesUrls: "/images/products/product-45.png",
  },
  {
    id: 46,
    tags: "Sustainable Materials",
    title: "Nike Go",
    description: "Women's Firm Support High Waisted Leggings with Pockets",
    color: "1 Colour",
    price: "MRP : ₹ 5 795.00",
    imagesUrls: "/images/products/product-46.png",
  },
  {
    id: 47,
    tags: "Just In",
    title: "NikeCourt Victory",
    description: "Women's Tennis Tank",
    color: "1 Colour",
    price: "MRP : ₹ 1 995.00",
    imagesUrls: "/images/products/product-47.png",
  },
  {
    id: 48,
    tags: "Just In",
    title: "Nike Alpha",
    description: "Women's High Support Padded Sports Bra",
    color: "1 Colour",
    price: "MRP : ₹ 3 695.00",
    imagesUrls: "/images/products/product-48.png",
  },
  {
    id: 49,
    tags: "Promo Exclusion",
    title: "Air Jordan 1 Mid SE",
    description: "Men's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 12 295.00",
    imagesUrls: "/images/products/product-49.png",
  },
  {
    id: 50,
    tags: "",
    title: "Nike Air Max 270 GO",
    description: "Baby/Toddler Easy On/Off Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 6 995.00",
    imagesUrls: "/images/products/product-50.png",
  },
  {
    id: 51,
    tags: "Just In",
    title: "Nike Invincible 3 By You",
    description: "Custom Men's Road Running Shoes",
    color: "6 Colours",
    price: "MRP : ₹ 19 295.00",
    imagesUrls: "/images/products/product-51.png",
  },
  {
    id: 52,
    tags: "Sustainable Materials",
    title: "Nike Air Max TW SE",
    description: "Men's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 15 995.00",
    imagesUrls: "/images/products/product-52.png",
  },
  {
    id: 53,
    tags: "Just In",
    title: "Nike Invincible 3 By You",
    description: "Custom Women's Road Running Shoes",
    color: "6 Colours",
    price: "MRP : ₹ 19 295.00",
    imagesUrls: "/images/products/product-53.png",
  },
  {
    id: 54,
    tags: "Just In",
    title: "Nike Air Max 90 Futura By You",
    description: "Custom Women's Shoes",
    color: "6 Colours",
    price: "MRP : ₹ 17 295.00",
    imagesUrls: "/images/products/product-54.png",
  },
  {
    id: 55,
    tags: "Just In",
    title: "Nike React Infinity 3 By You",
    description: "Custom Men's Road Running Shoes",
    color: "5 Colours",
    price: "MRP : ₹ 16 995.00",
    imagesUrls: "/images/products/product-55.png",
  },
  {
    id: 56,
    tags: "",
    title: "Nike Air Max 90 SE",
    description: "Men's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 12 795.00",
    imagesUrls: "/images/products/product-56.png",
  },
  {
    id: 57,
    tags: "Just In",
    title: "Nike Blazer Mid '77 Unlocked By You",
    description: "Custom Men's Shoes",
    color: "9 Colours",
    price: "MRP : ₹ 13 295.00",
    imagesUrls: "/images/products/product-57.png",
  },
  {
    id: 58,
    tags: "Just In",
    title: "Nike React Infinity 3 By You",
    description: "Custom Men's Road Running Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 16 995.00",
    imagesUrls: "/images/products/product-58.png",
  },
  {
    id: 59,
    tags: "Just In",
    title: "Nike Blazer Mid '77 Unlocke'd By You",
    description: "Custom Women's Shoes",
    color: "8 Colours",
    price: "MRP : ₹ 13 295.00",
    imagesUrls: "/images/products/product-59.png",
  },
  {
    id: 60,
    tags: "",
    title: "Nike Pegasus Trail 4 GORE-TEX",
    description: "Men's Waterproof Trail-Running Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 14 995.00",
    imagesUrls: "/images/products/product-60.png",
  },
  {
    id: 61,
    tags: "Just In",
    title: "Nike React Infinity 3 By You",
    description: "Custom Women's Road Running Shoes",
    color: "6 Colours",
    price: "MRP : ₹ 16 995.00",
    imagesUrls: "/images/products/product-61.png",
  },
  {
    id: 62,
    tags: "",
    title: "Nike Wildhorse 8",
    description: "Women's Trail Running Shoes",
    color: "2 Colours",
    price: "MRP : ₹ 11 895.00",
    imagesUrls: "/images/products/product-62.png",
  },
  {
    id: 63,
    tags: "Member Access",
    title: "Air Jordan 1 Mid SE Craft",
    description: "Men's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 12 295.00",
    imagesUrls: "/images/products/product-63.png",
  },
  {
    id: 64,
    tags: "",
    title: "Air Jordan XXXVII Low PF",
    description: "Men's Basketball Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 16 295.00",
    imagesUrls: "/images/products/product-64.png",
  },
  {
    id: 65,
    tags: "Member Access",
    title: "Zion 2 PF",
    description: "Men's Basketball Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
    imagesUrls: "/images/products/product-65.png",
  },
  {
    id: 66,
    tags: "",
    title: "Nike Gripknit Phantom GX Elite ,Fusion FG",
    description: "Firm-Ground Football Boot",
    color: "1 Colour",
    price: "MRP : ₹ 21 995.00",
    imagesUrls: "/images/products/product-66.png",
  },
  {
    id: 67,
    tags: "",
    title: "Nike Air Max 97 SE",
    description: "Men's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 17 495.00",
    imagesUrls: "/images/products/product-67.png",
  },
  {
    id: 68,
    tags: "",
    title: "Nike Pegasus Trail 4",
    description: "Men's Trail-Running Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 11 595.00",
    imagesUrls: "/images/products/product-68.png",
  },
  {
    id: 69,
    tags: "",
    title: "Nike Air Max 270 GO",
    description: "Younger Kids' Easy On/Off Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 7 995.00",
    imagesUrls: "/images/products/product-69.png",
  },
  {
    id: 70,
    tags: "",
    title: "Jordan Delta 3 Low SE",
    description: "Women's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 12 795.00",
    imagesUrls: "/images/products/product-70.png",
  },
  {
    id: 71,
    tags: "",
    title: "Nike Zegama",
    description: "Men's Trail-Running Shoes",
    color: "2 Colours",
    price: "MRP : ₹ 13 995.00",
    imagesUrls: "/images/products/product-71.png",
  },
  {
    id: 72,
    tags: "Member Access",
    title: "NikeCourt Air Zoom Vapor 9.5 Tour Premium",
    description: "Men's Tennis Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 15 995.00",
    imagesUrls: "/images/products/product-72.png",
  },
  {
    id: 73,
    tags: "",
    title: "Nike Sportswear",
    description: "Women's Ribbed Jersey Short Sleeve Top",
    color: "2 Colours",
    price: "MRP : ₹ 3 295.00",
    imagesUrls: "/images/products/product-73.png",
  },
  {
    id: 74,
    tags: "",
    title: "Nike Sportswear",
    description: "Women's High Waisted Ribbed Jersey Trousers",
    color: "1 Colour",
    price: "MRP : ₹ 3 995.00",
    imagesUrls: "/images/products/product-74.png",
  },
  {
    id: 75,
    tags: "Sustainab,le Materials",
    title: "Nike Air",
    description: "Women's Jumpsuit",
    color: "1 Colour",
    price: "MRP : ₹ 6 295.00",
    imagesUrls: "/images/products/product-75.png",
  },
  {
    id: 76,
    tags: "Sustainable Materials",
    title: "Nike Air",
    description: "Women's Woven Jacket",
    color: "1 Colour",
    price: "MRP : ₹ 7 295.00",
    imagesUrls: "/images/products/product-76.png",
  },
  {
    id: 77,
    tags: "",
    title: "Nike Sportswear",
    description: "Older Kids' (Girls') T-Shirt",
    color: "1 Colour",
    price: "MRP : ₹ 1 295.00",
    imagesUrls: "/images/products/product-77.png",
  },
  {
    id: 78,
    tags: "",
    title: "Nike Sportswear",
    description: "Women's High Waisted Ribbed Jersey Shorts",
    color: "1 Colour",
    price: "MRP : ₹ 2 495.00",
    imagesUrls: "/images/products/product-78.png",
  },
  {
    id: 79,
    tags: "Just In",
    title: "Jordan Series",
    description: "Women's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 7 495.00",
    imagesUrls: "/images/products/product-79.png",
  },
  {
    id: 80,
    tags: "Just In",
    title: "Nike Brasilia JDI",
    description: "Kids' Mini Backpack (11L)",
    color: "2 Colours",
    price: "MRP : ₹ 1 595.00",
    imagesUrls: "/images/products/product-80.png",
  },
  {
    id: 81,
    tags: "Just In",
    title: "Nike Air Max Excee",
    description: "Women's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 7 995.00",
    imagesUrls: "/images/products/product-81.png",
  },
  {
    id: 82,
    tags: "Promo Exclusion",
    title: "Nike Air Force 1 Low Retro",
    description: "Men's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 13 995.00",
    imagesUrls: "/images/products/product-82.png",
  },
  {
    id: 83,
    tags: "Just In",
    title: "Nike Sunray Protect 2",
    description: "Baby/Toddler Sandals",
    color: "2 Colours",
    price: "MRP : ₹ 2 495.00",
    imagesUrls: "/images/products/product-83.png",
  },
  {
    id: 84,
    tags: "Just In",
    title: "Nike City Rep TR",
    description: "Men's Training Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 4 995.00",
    imagesUrls: "/images/products/product-84.png",
  },
  {
    id: 85,
    tags: "Just In",
    title: "Nike Dri-FIT AeroBill",
    description: "Women's Golf Visor",
    color: "2 Colours",
    price: "MRP : ₹ 1 295.00",
    imagesUrls: "/images/products/product-85.png",
  },
  {
    id: 86,
    tags: "Just In",
    title: "Nike SuperRep Go 3 Next Nature Flyknit",
    description: "Men's Training Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 8 895.00",
    imagesUrls: "/images/products/product-86.png",
  },
  {
    id: 87,
    tags: "Just In",
    title: "Nike Dri-FIT Academy 23",
    description: "Women's Football Shorts",
    color: "1 Colour",
    price: "MRP : ₹ 1 595.00",
    imagesUrls: "/images/products/product-87.png",
  },
  {
    id: 88,
    tags: "Just In",
    title: "Nike Air Max SYSTM",
    description: "Men's Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 8 595.00",
    imagesUrls: "/images/products/product-88.png",
  },
  {
    id: 89,
    tags: "Just In",
    title: "Nike Dri-FIT Academy",
    description: "Older Kids' Woven Football Tracksuit Bottoms (Stock)",
    color: "1 Colour",
    price: "MRP : ₹ 2 195.00",
    imagesUrls: "/images/products/product-89.png",
  },
  {
    id: 90,
    tags: "Sustainable Mater,ials",
    title: "NikeCourt Legacy",
    description: "Men's Shoes",
    color: "2 Colours",
    price: "MRP : ₹ 5 695.00",
    imagesUrls: "/images/products/product-90.png",
  },
];